### Register User
POST http://localhost:6600/api/auth/register
Content-Type: application/json

{
    "username": "test3",
    "email": "test3@gmail.com",
    "password": "123123"
}



### Login User
POST http://localhost:6600/api/auth/login
Content-Type: application/json

{
    "email": "test2@gmail.com",
    "password": "123"
}



### Logout user -> authController.js
POST http://localhost:6600/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWI5MTIwZmYzM2MzMjgzYjdhODY4NzUiLCJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImlhdCI6MTc3MzczNjQ4OSwiZXhwIjoxNzczNzQwMDg5fQ.VSdJpaQ8EMPE_rQf3ROVHYiWwzqcUuQQtKPDX9mgg70



### Get current user -> authController.js
GET http://localhost:6600/api/auth/getuser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWI4ZTAyODQ0MjE2ZDI1YmQyMjJlMjQiLCJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImlhdCI6MTc3MzcyNjYxMiwiZXhwIjoxNzczNzMwMjEyfQ.uLNdr4-xPrVqrf3p1SJMoOnxq5msTFYZObXtPEJGGn0

### Room creation
POST http://localhost:6600/api/room/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWI5MTIwZmYzM2MzMjgzYjdhODY4NzUiLCJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImlhdCI6MTc3NDMzMTE1NSwiZXhwIjoxNzc0MzM0NzU1fQ.GIaMKzcHM4qXmsHl-yHONa1accVYK1AX3C5YgHfjxPs

{
    "title": "test1",
    "password": "123",
    "language": "JavaScript",
    "userId": "69b83db6c7f00862106e660a"
}



### Room Joining
POST http://localhost:6600/api/room/join
Content-Type: application/json

{
    "roomId": "vi9588",
    "password": "123",
    "userId": "69b83db6c7f00862106e660a"
}


### Compiler Req
POST http://localhost:6600/api/compile/run
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OWI5MTIwZmYzM2MzMjgzYjdhODY4NzUiLCJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImlhdCI6MTc3NDMzMTE1NSwiZXhwIjoxNzc0MzM0NzU1fQ.GIaMKzcHM4qXmsHl-yHONa1accVYK1AX3C5YgHfjxPs

{
  "code": "print('Hello World')",
  "languageId": 71,
  "input": ""
}